name: Deploy Helios-API
on:
  push:
    branches:
      - main
jobs:
  trufflehog:
    name: trufflehog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
  tests:
    name: Tests
    runs-on: ${{ vars.RUNS_ON }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Tests
        run: mvn test

